application: 
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email:
  base_url: "localhost"
  sender_email: "not-an-email@yyy.com"
  auth_token: "super-secret-token"
  timeout_milliseconds: 1000
